#!/usr/bin/env bash
#
# Builds a campaign app (generated by gen-rn-app.sh / gen-expo-app.sh) for one
# target. No device is touched, so no device lock is taken.
#
#   build-app.sh <app dir> <target>...
#
# Targets:
#   android-debug       :app:assembleDebug   (arm64-v8a)
#   android-release     :app:assembleRelease (arm64-v8a, -PbugseeE2eDebuggable=true),
#                       then the 16 KB alignment check (check-16kb.sh): a
#                       Bugsee library out of alignment fails the target;
#                       only another vendor's records PASS-16KB-WARN
#   ios-sim-debug       Debug, iphonesimulator
#   ios-sim-release     Release, iphonesimulator
#   ios-device-debug    Debug, iphoneos, signed for IOS_DEVELOPMENT_TEAM
#   ios-device-release  Release, iphoneos, signed for IOS_DEVELOPMENT_TEAM
#   all                 the five the plan asks for: android-debug,
#                       android-release, ios-sim-debug, ios-device-debug,
#                       ios-device-release
#
# Environment:
#   IOS_DEVELOPMENT_TEAM  default 7LJD5DCH7T (device targets only)
#   ANDROID_HOME          default ~/Library/Android/sdk
#
# Each target writes <campaign-apps>/logs/<app>-<target>.log and one result
# line to <campaign-apps>/logs/build-results.tsv:
#   <UTC> <app> <target> PASS|FAIL <seconds> <artifact> <sha256>
set -uo pipefail

# One function, so bash parses the whole script before running any of it.
main() {
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${1:?usage: build-app.sh <app dir> <target>...}" && pwd)" || exit 2
shift
APP="$(basename "$APP_DIR")"
LOGS="$(dirname "$APP_DIR")/logs"
mkdir -p "$LOGS"
RESULTS="$LOGS/build-results.tsv"
: "${ANDROID_HOME:=$HOME/Library/Android/sdk}"
export ANDROID_HOME
TEAM="${IOS_DEVELOPMENT_TEAM:-7LJD5DCH7T}"

PORT="$(cat "$APP_DIR/campaign.port" 2>/dev/null || echo 8081)"
TARGETS=("$@")
if [[ "${TARGETS[0]:-}" == all ]]; then
  TARGETS=(android-debug android-release ios-sim-debug ios-device-debug ios-device-release)
fi

workspace() { ls -d "$APP_DIR"/ios/*.xcworkspace | head -1; }
scheme() { basename "$(workspace)" .xcworkspace; }

record() { # target status seconds artifact
  local sha="-"
  [[ -e "$4" && -f "$4" ]] && sha="$(shasum -a 256 "$4" | cut -c1-16)"
  [[ -d "$4" ]] && sha="$(find "$4" -type f -name "$(basename "$4" .app)" -exec shasum -a 256 {} \; | cut -c1-16)"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$APP" "$1" "$2" "$3" "${4#$APP_DIR/}" "$sha" >>"$RESULTS"
  echo "$APP $1: $2 (${3}s) ${4#$APP_DIR/}"
}

xcode() { # configuration sdk destination log [extra settings...]
  local cfg="$1" sdk="$2" dest="$3" log="$4"
  shift 4
  xcodebuild -workspace "$(workspace)" -scheme "$(scheme)" -configuration "$cfg" \
    -sdk "$sdk" -destination "$dest" -derivedDataPath "$APP_DIR/ios/build" \
    "$@" build >"$log" 2>&1
}

overall=0
for target in "${TARGETS[@]}"; do
  log="$LOGS/$APP-$target.log"
  start=$SECONDS
  artifact="-"
  case "$target" in
    android-debug)
      (cd "$APP_DIR/android" && ./gradlew :app:assembleDebug -PreactNativeArchitectures=arm64-v8a -PreactNativeDevServerPort="$PORT") >"$log" 2>&1
      rc=$?
      artifact="$APP_DIR/android/app/build/outputs/apk/debug/app-debug.apk"
      ;;
    android-release)
      (cd "$APP_DIR/android" && ./gradlew :app:assembleRelease -PreactNativeArchitectures=arm64-v8a -PbugseeE2eDebuggable=true) >"$log" 2>&1
      rc=$?
      artifact="$APP_DIR/android/app/build/outputs/apk/release/app-release.apk"
      if [[ $rc -eq 0 ]]; then
        "$HERE/check-16kb.sh" "$artifact" >>"$log" 2>&1 || rc=$?
        if [[ $rc -eq 4 ]]; then
          record "$target" PASS-16KB-WARN $((SECONDS - start)) "$artifact"
          grep "16 KB check" "$log"
          continue
        fi
      fi
      ;;
    ios-sim-debug|ios-sim-release)
      cfg=Debug; [[ "$target" == *release ]] && cfg=Release
      xcode "$cfg" iphonesimulator "generic/platform=iOS Simulator" "$log"
      rc=$?
      artifact="$APP_DIR/ios/build/Build/Products/${cfg}-iphonesimulator/$(scheme).app"
      # Same embed assertion as the device targets and run-ios.sh: a link or
      # embed miss fails here, not later as a silent launch.
      if [[ $rc -eq 0 ]]; then
        node "$HERE/../cli-assert-framework-embedded.ts" "$artifact" >>"$log" 2>&1 || rc=$?
      fi
      ;;
    ios-device-debug|ios-device-release)
      cfg=Debug; [[ "$target" == *release ]] && cfg=Release
      xcode "$cfg" iphoneos "generic/platform=iOS" "$log" \
        DEVELOPMENT_TEAM="$TEAM" CODE_SIGN_STYLE=Automatic -allowProvisioningUpdates
      rc=$?
      artifact="$APP_DIR/ios/build/Build/Products/${cfg}-iphoneos/$(scheme).app"
      if [[ $rc -eq 0 ]]; then
        node "$HERE/../cli-assert-framework-embedded.ts" "$artifact" >>"$log" 2>&1 || rc=$?
      fi
      ;;
    *) echo "unknown target $target" >&2; exit 2 ;;
  esac
  if [[ $rc -eq 0 ]]; then
    record "$target" PASS $((SECONDS - start)) "$artifact"
  else
    record "$target" FAIL $((SECONDS - start)) "$artifact"
    grep -E "error:|FAILED|What went wrong|^> |FAIL" "$log" | cut -c1-300 | head -15
    overall=1
  fi
done
exit $overall
}

main "$@"
