/**
 * Same rule as `isPlaceholderToken` in examples/bare/endpoint.ts. The CI
 * token `00000000-0000-4000-8000-000000000000` matches. Copied here so the
 * plugin does not import the example app.
 */
const PLACEHOLDER_TOKEN = /^0{12}[0-9a-f]0{3}[0-9a-f]0{15}$/i;

export function isPlaceholderToken(token: string): boolean {
  return PLACEHOLDER_TOKEN.test(token.replace(/-/g, ''));
}

export interface PropertiesInput {
  readonly appToken?: string;
  /** Defaults on. Opt out with `false`. */
  readonly nativeCrashReporting?: boolean;
}

/**
 * `<rootProject>/bugsee.properties`. The token is the unprefixed `app_token`
 * key. `plugin.ndk.enabled=true` is written only for a real, non-placeholder
 * token while native crash reporting is on (the default). `plugin.appToken`
 * is not a key the Gradle plugin reads, and this file never emits it.
 * No endpoint key: a placeholder token omits the upload flag instead of
 * pointing the build at another host.
 */
export function bugseePropertiesText(input: PropertiesInput = {}): string {
  const token = input.appToken ?? '';
  const lines: string[] = [];
  if (token.length > 0) {
    lines.push(`app_token=${token}`);
  }
  const ndkOn = input.nativeCrashReporting !== false;
  if (ndkOn && token.length > 0 && !isPlaceholderToken(token)) {
    lines.push('plugin.ndk.enabled=true');
  }
  if (lines.length === 0) {
    return '# Generated by @bugsee/react-native. No app token configured.\n';
  }
  return `${lines.join('\n')}\n`;
}
