import androidEnums from '../../packages/react-native/src/options/option-enums.json';
import iosEnums from '../../packages/react-native/src/options/ios-enums.json';

/**
 * Nothing compared the two platforms' enums until this existed.
 *
 * The option-enum fixture is extracted from the ANDROID sources, so a
 * divergence on iOS was structurally invisible to us -- the same
 * "a check that can only see one configuration" shape that has already cost
 * this repo a CocoaPods build and an afternoon on a device.
 *
 * It is not a theoretical risk. iOS renumbered `BugseeLifecycleEventType`
 * between 7.0.0-beta1 and beta2. An enum both SDKs accept but number
 * differently raises no error anywhere: the SDK honours the value, and the
 * report simply says something other than what the caller meant.
 *
 * Both fixtures are regenerated by `scripts/cli-extract-option-keys.ts` from
 * the two SDK checkouts, so bumping a native version refreshes them together.
 */

/** iOS prefixes every member; Android's names are bare. */
const stripPrefix = (member: string): string =>
  member.replace(/^(?:BugseeSeverity|BGSIssueType)/, '');

const byValue = (members: Record<string, number>): Record<number, string> =>
  Object.fromEntries(Object.entries(members).map(([name, value]) => [value, name]));

describe('IssueSeverity agrees across platforms', () => {
  const ios = iosEnums.IssueSeverity as Record<string, number>;
  const android = androidEnums.IssueSeverity as Record<string, number>;

  /**
   * VALUES, not names. This is the assertion that matters: we coerce by value,
   * so a report carrying severity 3 must mean the same thing on both
   * platforms. A by-name comparison would fail on a cosmetic rename and pass
   * on a renumbering, which is exactly backwards.
   */
  it('assigns the same set of values', () => {
    expect(Object.values(ios).sort()).toEqual(Object.values(android).sort());
  });

  /**
   * Names agree except at value 1, which iOS calls `Low` and Android
   * `VeryLow`. Listed as a KNOWN, single exception rather than tolerated
   * loosely: an exception list that silently absorbs new entries is worse than
   * no gate, because it looks like coverage. A second divergence fails here.
   *
   * The divergence is itself a parity defect -- every wrapper must choose one
   * name for a cross-platform enum, and each will choose differently, which is
   * how a by-name binding acquires a hole at value 1.
   */
  it('names agree except for the one known divergence at value 1', () => {
    const KNOWN_ALIASES: Record<string, string> = { Low: 'VeryLow' };
    const iosNames = Object.fromEntries(
      Object.entries(byValue(ios)).map(([value, member]) => {
        const bare = stripPrefix(member);
        return [value, KNOWN_ALIASES[bare] ?? bare];
      }),
    );

    expect(iosNames).toEqual(byValue(android));
  });

  /**
   * Losing this one is not hypothetical: a hand-written mapping in this
   * package once dropped `Blocker` and shifted three values, each of which the
   * SDK still accepted as a valid severity.
   */
  it('keeps Blocker as the highest value on both', () => {
    expect(android.Blocker).toBe(5);
    expect(ios.BugseeSeverityBlocker).toBe(5);
  });
});

/**
 * iOS declares this enum and uses it nowhere -- the type travels as an
 * NSString on the internal request and never reaches BGSReportContract, so an
 * iOS handler cannot tell a recovered crash from a bug report the user typed.
 * Tracked as bugsee-cocoa#121.
 *
 * Pinned anyway, because the values already agree and that is worth keeping
 * true: whichever representation lands, it will have to match these.
 */
describe('IssueType agrees across platforms', () => {
  it('numbers Bug, Crash and Error identically', () => {
    expect(
      Object.fromEntries(
        Object.entries(iosEnums.IssueType as Record<string, number>)
          .map(([member, value]) => [stripPrefix(member), value]),
      ),
    ).toEqual({ Bug: 0, Crash: 1, Error: 2 });
  });
});
