/**
 * The smallest app that proves Phase 1: launch the SDK and show what the
 * native side reports back.
 *
 * It prints `BUGSEE_E2E status=<n>` on every status change. That line is the
 * e2e's only contract with the app (see e2e/launch.test.ts) — asserting on it
 * from the device log keeps the test honest about what the *native* SDK did,
 * rather than about what JS believes it asked for.
 *
 * What it does after launching is picked by a scenario (e2e/scenario.ts):
 * `launch`, the default, is the lifecycle walk launch.test.ts asserts; the
 * `rh-*` scenarios are the report-handler cases in scenarios/report-handler.ts;
 * `channel` is scenarios/channel.ts, `console` is scenarios/console.ts,
 * `data` is scenarios/data.ts, `network` is scenarios/network.ts, `secure`
 * is scenarios/secure.tsx, `attributes`/`attributes-persist` are
 * scenarios/attributes.ts, `e2e-native-smoke` / `native-crash-*` are
 * scenarios/native.ts, `blackout`, `blackout-prelaunch`,
 * `secure-component` and `view-tree` are scenarios/privacy.tsx, and
 * `exc-*` are scenarios/exceptions.tsx, `rp-*` are
 * scenarios/reporting.ts, `log-filter` is scenarios/log-filter.ts, and
 * `network-filter` is scenarios/network-filter.ts.
 */
import { useEffect, useState } from 'react';
import {
  Linking,
  Platform,
  Settings,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import Bugsee, {
  BugseeLaunchOptions,
  Status,
  createDefaultLaunchOptions,
  type LaunchOptions,
} from '@bugsee/react-native';

// Generated by scripts/write-credentials.mjs from the environment; gitignored.
import credentials from './credentials.json';
import { DEAD_ENDPOINT, isPlaceholderToken, launchEndpoint } from './endpoint';
// Written by the device e2e before each run (default by write-credentials);
// gitignored.
import scenarioFile from './e2e-scenario.json';
import {
  installReportHandler,
  isReportHandlerScenario,
  runReportHandlerScenario,
} from './scenarios/report-handler';
import {
  isChannelScenario,
  preLaunchChannelProbe,
  runChannelScenario,
} from './scenarios/channel';
import { isConsoleScenario, runConsoleScenario } from './scenarios/console';
import {
  isDataScenario,
  preLaunchDataProbe,
  runDataScenario,
} from './scenarios/data';
import { isNetworkScenario, runNetworkScenario } from './scenarios/network';
import { SecureProbe, isSecureScenario } from './scenarios/secure';
import {
  isAttributeScenario,
  runAttributeScenario,
} from './scenarios/attributes';
import {
  installNativeHandler,
  isNativeScenario,
  runNativeScenario,
} from './scenarios/native';
import {
  PrivacyStage,
  type PrivacyScenario,
  isPrivacyScenario,
  preLaunchPrivacyProbe,
  runPrivacyScenario,
} from './scenarios/privacy';
import {
  ExceptionStage,
  installExceptionAppHandler,
  isExceptionRenderScenario,
  isExceptionScenario,
  preLaunchExceptionProbe,
  runExceptionScenario,
} from './scenarios/exceptions';
import {
  installReporting,
  isReportingScenario,
  runReportingScenario,
} from './scenarios/reporting';
import {
  isLogFilterScenario,
  runLogFilterScenario,
} from './scenarios/log-filter';
import {
  installNetworkFilter,
  isNetworkFilterScenario,
  runNetworkFilterScenario,
} from './scenarios/network-filter';

const STATUS_NAMES: Record<number, string> = {
  [Status.Stopped]: 'Stopped',
  [Status.Launching]: 'Launching',
  [Status.Launched]: 'Launched',
  [Status.Stopping]: 'Stopping',
};

/**
 * A recording duration the SDK does not default to, so reading it back proves
 * the option actually crossed the bridge rather than the SDK reporting its own
 * default at us. Android defaults to 60.
 */
const NON_DEFAULT_DURATION = 90;

/**
 * The launch payload, built through the typed options model.
 *
 * The endpoint is the one option whose key differs per platform, and the two
 * SDKs disagree about the version segment. That belongs in the library, not
 * here -- this file carried its own copy of the rule until the model grew one.
 */
function launchOptions(endpoint: string): LaunchOptions {
  const options = createDefaultLaunchOptions();
  options.endpoint = endpoint;
  options.duration = NON_DEFAULT_DURATION;
  return BugseeLaunchOptions.serialize(options) as LaunchOptions;
}

function appToken(): string {
  return Platform.OS === 'ios' ? credentials.ios : credentials.android;
}

interface ScenarioChoice {
  scenario: string;
  nonce: string;
  source: 'uri' | 'args' | 'json';
  /**
   * An endpoint to launch against instead of the credentials' one. iOS has
   * no airplane mode the e2e can switch (none at all on the simulator), so
   * the e2e retains a report there by pointing the SDK at a closed loopback
   * port (see e2e/bundles.ts).
   */
  endpoint?: string;
}

const SCENARIO_URI =
  /^bugsee-e2e:\/\/scenario\/([\w-]+)\?nonce=([0-9a-f]+)(?:&endpoint=([\w%.-]+))?$/;

/**
 * iOS's per-launch channel: the launch arguments `-bugseeE2eScenario <name>
 * -bugseeE2eNonce <hex> [-bugseeE2eEndpoint <url>]`, which iOS puts in
 * NSUserDefaults' volatile argument domain and `Settings` reads back. The
 * iOS counterpart of the Android URI, and needed for the same reason: on a
 * physical iPhone the Debug app runs its embedded bundle whenever it cannot
 * reach Metro (no Local Network permission, another network), and that
 * bundle's JSON was baked in at build time. `Settings` reads the merged
 * defaults; the e2e only ever populates these keys through the volatile
 * argument domain, and nothing writes them, so a later launch that is not
 * given them does not see them. Validated as the URI's fields are.
 */
function launchArguments(): ScenarioChoice | undefined {
  if (Platform.OS !== 'ios') {
    return undefined;
  }
  const scenario: unknown = Settings.get('bugseeE2eScenario');
  const nonce: unknown = Settings.get('bugseeE2eNonce');
  const endpoint: unknown = Settings.get('bugseeE2eEndpoint');
  if (
    typeof scenario !== 'string' ||
    typeof nonce !== 'string' ||
    !/^[\w-]+$/.test(scenario) ||
    !/^[0-9a-f]+$/.test(nonce)
  ) {
    return undefined;
  }
  return {
    scenario,
    nonce,
    source: 'args',
    endpoint:
      typeof endpoint === 'string' && /^https?:\/\/\S+$/.test(endpoint)
        ? endpoint
        : undefined,
  };
}

/**
 * The launch intent's `bugsee-e2e://scenario/<name>?nonce=<hex>[&endpoint=<url,
 * percent-encoded>]` when there is
 * one (Android), else the launch arguments (iOS), else e2e-scenario.json. The
 * per-launch channels exist for builds that bake the JSON in at build time --
 * an Android release build, an iPhone Debug build away from Metro -- and so
 * cannot be steered per launch through it.
 */
async function chooseScenario(): Promise<ScenarioChoice> {
  const uri = await Linking.getInitialURL().catch(() => null);
  const match = uri === null ? null : SCENARIO_URI.exec(uri);
  if (match !== null) {
    return {
      scenario: match[1]!,
      nonce: match[2]!,
      source: 'uri',
      endpoint: match[3] === undefined ? undefined : decodeURIComponent(match[3]),
    };
  }
  const args = launchArguments();
  if (args !== undefined) {
    return args;
  }
  // Widened: with the file present, TS types it from whatever it holds now,
  // and the default has no nonce.
  const file: { scenario: string; nonce?: string; endpoint?: string } =
    scenarioFile;
  return {
    scenario: file.scenario,
    nonce: file.nonce ?? '-',
    source: 'json',
    endpoint: file.endpoint,
  };
}

export default function App() {
  const [status, setStatus] = useState<number>(Status.Stopped);
  const [error, setError] = useState<string | undefined>();
  /** Set by the `secure` scenario once Launched: mounts the probe. */
  const [secureNonce, setSecureNonce] = useState<string | undefined>();
  /**
   * Set as soon as a privacy scenario is chosen: its white stage covers the
   * screen from before launch, and its probes mount once Launched.
   */
  const [privacy, setPrivacy] = useState<
    { scenario: PrivacyScenario; nonce: string; launched: boolean } | undefined
  >();
  /**
   * Set once Launched for `exc-boundary` / `exc-root`: mounts the thrower
   * (with or without an app ErrorBoundary).
   */
  const [exceptionRender, setExceptionRender] = useState<
    { scenario: 'exc-boundary' | 'exc-root'; nonce: string } | undefined
  >();

  useEffect(() => {
    let cancelled = false;
    let poll: ReturnType<typeof setInterval> | undefined;

    // Resolved by `observe` the first time it LOGS Launched -- not the first
    // time a poll sees it. A second, independent poll would return earlier
    // than this one logs, putting `relaunch() resolved` ahead of `status=2`
    // in the output, which an ordered e2e cannot match.
    let announceLaunched: () => void;
    const loggedLaunched = new Promise<void>(resolve => {
      announceLaunched = resolve;
    });

    const observe = (next: number) => {
      if (cancelled) {
        return;
      }
      setStatus(previous => {
        if (previous !== next) {
          // The e2e's marker. Also the only way to see the Launching →
          // Launched transition on a device without attaching a debugger.
          console.log(`BUGSEE_E2E status=${next} (${STATUS_NAMES[next]})`);
          if (next === Status.Launched) {
            // Not announceLaunched() itself. This updater runs inside the
            // getStatus bridge callback, and resolving here resumes the
            // launch sequence on that same turn. console.log from that
            // continuation never reaches the console: CI shows the option
            // read-back simply absent, then relaunch's own lines. A
            // macrotask resumes the sequence after the bridge call returns.
            setTimeout(announceLaunched, 0);
          }
        }
        return next;
      });
    };

    (async () => {
      const token = appToken();
      if (!token) {
        setError(`no ${Platform.OS} token — run scripts/write-credentials.mjs`);
        return;
      }
      const choice = await chooseScenario();
      // A placeholder token never reaches the real server (endpoint.ts).
      const { endpoint, forced } = launchEndpoint(
        token,
        choice.endpoint,
        credentials.endpoint,
      );
      // The e2e matches the nonce here before anything else, so a stale
      // bundle or scenario file cannot pass for this run. `dev` says whether
      // a red box can swallow a crash -- the case that needs a release build
      // asserts on it. `endpoint` is the one launch() gets.
      console.log(
        `BUGSEE_E2E scenario=${choice.scenario} nonce=${choice.nonce} ` +
          `source=${choice.source} dev=${String(__DEV__)} ` +
          `token=${isPlaceholderToken(token) ? 'placeholder' : 'set'} ` +
          `endpoint=${endpoint === '' ? 'default' : endpoint}`,
      );
      if (forced) {
        console.log(
          `BUGSEE_E2E placeholder token: launching against ${DEAD_ENDPOINT}, ` +
            `not ${choice.endpoint ?? (credentials.endpoint || 'the default endpoint')}`,
        );
      }
      const reportHandler = isReportHandlerScenario(choice.scenario)
        ? choice.scenario
        : undefined;
      const channel = isChannelScenario(choice.scenario)
        ? choice.scenario
        : undefined;
      const data = isDataScenario(choice.scenario) ? choice.scenario : undefined;
      const privacyScenario = isPrivacyScenario(choice.scenario)
        ? choice.scenario
        : undefined;
      if (privacyScenario !== undefined && !cancelled) {
        setPrivacy({ scenario: privacyScenario, nonce: choice.nonce, launched: false });
      }
      // Before launch(): a report the SDK recovers at launch is only offered
      // to a handler that is already registered.
      if (reportHandler !== undefined) {
        installReportHandler(reportHandler, choice.nonce);
      }
      // Before launch(): the channel scenario's negative case -- a line sent
      // here must be dropped, since nothing is buffered before the SDK is up.
      if (channel !== undefined) {
        preLaunchChannelProbe(choice.nonce);
      }
      // Before launch(): the data scenario's negative case -- a log line,
      // event and trace sent here must not reach the bundle.
      if (data !== undefined) {
        preLaunchDataProbe(choice.nonce);
      }
      // Before launch(): blackout-prelaunch's startBlackout(), and the
      // blackout lifecycle subscription.
      if (privacyScenario !== undefined) {
        preLaunchPrivacyProbe(privacyScenario, choice.nonce);
      }
      // Before launch(): a crash recovered at the next launch only reaches a
      // handler that is already registered (Task 7.6b).
      if (isNativeScenario(choice.scenario)) {
        installNativeHandler(choice.scenario);
      }
      // Before launch(): app ErrorUtils handler (so Bugsee chains to it), and
      // the pre-launch exception probe (must not reach a bundle).
      if (isExceptionScenario(choice.scenario)) {
        installExceptionAppHandler();
        if (choice.scenario === 'exc-prelaunch') {
          preLaunchExceptionProbe(choice.nonce);
        }
      }
      // Before launch(): rp-prelaunch's upload and dialog, and the handlers
      // the other reporting scenarios need already registered.
      if (isReportingScenario(choice.scenario)) {
        installReporting(choice.scenario, choice.nonce);
      }
      // Before launch(): the network filter has to be installed before the
      // SDK's own session and Metro's websocket are captured.
      if (isNetworkFilterScenario(choice.scenario)) {
        installNetworkFilter(choice.nonce);
      }
      console.log(`BUGSEE_E2E launching on ${Platform.OS}`);
      // Polling starts before launch() is awaited, not after. The SDK brings
      // capture up off the main thread, so by the time the promise resolves the
      // status is usually already Launched and the Launching state would never
      // be observed — the very transition this example exists to show.
      poll = setInterval(() => {
        Bugsee.getStatus().then(observe).catch(() => {});
      }, 100);
      try {
        const launched = await Bugsee.launch(token, launchOptions(endpoint));
        console.log(`BUGSEE_E2E launch() resolved ${String(launched)}`);

        // Wait for Launched to be LOGGED before relaunching, so the output
        // order is deterministic: status=2, then relaunch, then status=2
        // again. Firing relaunch as soon as launch() resolves races the
        // status poll, and the e2e matches its steps in order.
        await loggedLaunched;

        if (reportHandler !== undefined) {
          runReportHandlerScenario(reportHandler, choice.nonce);
          return;
        }

        if (channel !== undefined) {
          runChannelScenario(choice.nonce);
          return;
        }

        if (isConsoleScenario(choice.scenario)) {
          runConsoleScenario(choice.nonce);
          return;
        }

        if (data !== undefined) {
          runDataScenario(choice.nonce);
          return;
        }

        if (isNetworkScenario(choice.scenario)) {
          await runNetworkScenario(choice.nonce);
          return;
        }

        if (isLogFilterScenario(choice.scenario)) {
          runLogFilterScenario(choice.nonce);
          return;
        }

        if (isAttributeScenario(choice.scenario)) {
          runAttributeScenario(choice.scenario, choice.nonce);
          return;
        }

        if (isNativeScenario(choice.scenario)) {
          runNativeScenario(choice.scenario, choice.nonce);
          return;
        }

        if (privacyScenario !== undefined) {
          if (!cancelled) {
            setPrivacy({ scenario: privacyScenario, nonce: choice.nonce, launched: true });
          }
          runPrivacyScenario(privacyScenario, choice.nonce);
          return;
        }

        if (isSecureScenario(choice.scenario)) {
          if (!cancelled) {
            setSecureNonce(choice.nonce);
          }
          return;
        }

        if (isReportingScenario(choice.scenario)) {
          runReportingScenario(choice.scenario, choice.nonce);
          return;
        }

        if (isNetworkFilterScenario(choice.scenario)) {
          runNetworkFilterScenario(choice.nonce);
          return;
        }

        if (isExceptionScenario(choice.scenario)) {
          if (isExceptionRenderScenario(choice.scenario)) {
            if (!cancelled) {
              setExceptionRender({
                scenario: choice.scenario,
                nonce: choice.nonce,
              });
            }
            return;
          }
          runExceptionScenario(choice.scenario, choice.nonce);
          return;
        }

        // Task 2.6: the option must have reached the SDK, not merely been
        // accepted by launch(). Reading it back through getLaunchOptions is
        // the only thing that shows the difference.
        //
        // The lines are held until relaunch() settles, then printed after
        // its own line. On the CI simulator the console.log in this
        // continuation, and the Debug NSLog inside getLaunchOptions, are
        // both absent from the pty while this function keeps going and the
        // relaunch continuation is present. The strings are taken before
        // relaunch, so they are still the options getLaunchOptions returned.
        // The relaunch line comes first: launch.test.ts waits up to 45s for
        // it and only then for these lines, so a hung started: callback
        // fails as relaunch rather than as a missing duration.
        let optionLines: string[];
        try {
          const effective = await Bugsee.getLaunchOptions();
          optionLines = [
            `BUGSEE_E2E effective duration=${String(
              effective['com.bugsee.option.config.duration'],
            )} keys=${Object.keys(effective).length}`,
            // Task 3.7: this app never sets wifi-only-upload (see
            // launchOptions above -- only endpoint and duration), so an SDK
            // that could only report options differing from its own defaults
            // would have no key to answer with here at all. Logged separately
            // from `effective duration` so a caller can tell "the getter
            // answered but the key is missing" from "the getter never ran".
            `BUGSEE_E2E effective wifi-only-upload=${String(
              effective['com.bugsee.option.config.wifi-only-upload'],
            )}`,
            // The endpoint as the SDK itself reports it: the witness that a
            // placeholder token was not sent to the real server.
            `BUGSEE_E2E effective endpoint ${JSON.stringify(
              Object.fromEntries(
                Object.keys(effective)
                  .filter(key => /endpoint/i.test(key))
                  .map(key => [key, effective[key]]),
              ),
            )}`,
          ];
        } catch (optionsCause) {
          optionLines = [`BUGSEE_E2E effective threw ${String(optionsCause)}`];
        }

        // relaunch() is the one lifecycle call whose two platforms settle
        // through different SDK machinery: Android hands back a boolean, iOS
        // reports through a `started:` completion block that the SDK can fail
        // to invoke. What the e2e asserts is that the promise SETTLES -- a
        // promise that never settles is indistinguishable from a slow one,
        // and no other check in this repo would notice.
        let relaunchLine: string;
        try {
          const relaunched = await Bugsee.relaunch(launchOptions(endpoint));
          relaunchLine = `BUGSEE_E2E relaunch() settled resolved=${String(relaunched)}`;
        } catch (relaunchCause) {
          relaunchLine = `BUGSEE_E2E relaunch() settled rejected=${String(relaunchCause)}`;
        }
        console.log(relaunchLine);
        for (const line of optionLines) {
          console.log(line);
        }

        // Asserted separately from the status poll: a successful relaunch
        // completes in about 10ms, so the 100ms poll observes no change and
        // logs nothing. Reading the status here is what proves capture
        // actually came back up.
        console.log(
          `BUGSEE_E2E post-relaunch status=${await Bugsee.getStatus()}`,
        );
      } catch (cause) {
        console.log(`BUGSEE_E2E launch() threw ${String(cause)}`);
        if (!cancelled) {
          setError(String(cause));
        }
      }
    })();

    return () => {
      cancelled = true;
      if (poll !== undefined) {
        clearInterval(poll);
      }
    };
  }, []);

  return (
    <View style={styles.screen}>
      <View style={styles.card}>
        <Text style={styles.title}>Bugsee React Native</Text>
        <Text style={styles.label}>status</Text>
        <Text testID="status" style={styles.status}>
          {STATUS_NAMES[status] ?? `unknown (${status})`}
        </Text>
        {error !== undefined && <Text style={styles.error}>{error}</Text>}
      </View>
      {secureNonce !== undefined && <SecureProbe nonce={secureNonce} />}
      {privacy !== undefined && (
        <PrivacyStage
          scenario={privacy.scenario}
          nonce={privacy.nonce}
          launched={privacy.launched}
        />
      )}
      {exceptionRender !== undefined && (
        <ExceptionStage
          scenario={exceptionRender.scenario}
          nonce={exceptionRender.nonce}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#11131a' },
  card: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  title: { color: '#8a94a6', fontSize: 16, marginBottom: 32 },
  label: { color: '#5c6577', fontSize: 12, letterSpacing: 2 },
  status: { color: '#f5f7fa', fontSize: 40, fontWeight: '600', marginTop: 8 },
  error: { color: '#ff6b6b', fontSize: 13, marginTop: 24, textAlign: 'center' },
});
