/**
 * The smallest app that proves Phase 1: launch the SDK and show what the
 * native side reports back.
 *
 * It prints `BUGSEE_E2E status=<n>` on every status change. That line is the
 * e2e's only contract with the app (see e2e/launch.test.ts) — asserting on it
 * from the device log keeps the test honest about what the *native* SDK did,
 * rather than about what JS believes it asked for.
 */
import { useEffect, useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import Bugsee, { Status, type LaunchOptions } from '@bugsee/react-native';

// Generated by scripts/write-credentials.mjs from the environment; gitignored.
import credentials from './credentials.json';

const STATUS_NAMES: Record<number, string> = {
  [Status.Stopped]: 'Stopped',
  [Status.Launching]: 'Launching',
  [Status.Launched]: 'Launched',
  [Status.Stopping]: 'Stopping',
};

/**
 * `endpoint` is the one option whose key differs per platform, and iOS insists
 * on a `/v2` suffix that Android must not get. Phase 2 moves this into the
 * typed options model so callers never see it; until then the example spells
 * it out rather than pretending the two platforms agree.
 */
function endpointOption(endpoint: string): LaunchOptions {
  if (!endpoint) {
    return {};
  }
  if (Platform.OS === 'ios') {
    const base = endpoint.replace(/\/+$/, '');
    return { endpoint: base.endsWith('/v2') ? base : `${base}/v2` };
  }
  return { 'com.bugsee.option.$$ENDPOINT': endpoint };
}

function appToken(): string {
  return Platform.OS === 'ios' ? credentials.ios : credentials.android;
}

export default function App() {
  const [status, setStatus] = useState<number>(Status.Stopped);
  const [error, setError] = useState<string | undefined>();

  useEffect(() => {
    let cancelled = false;
    let poll: ReturnType<typeof setInterval> | undefined;

    // Resolved by `observe` the first time it LOGS Launched -- not the first
    // time a poll sees it. A second, independent poll would return earlier
    // than this one logs, putting `relaunch() resolved` ahead of `status=2`
    // in the output, which an ordered e2e cannot match.
    let announceLaunched: () => void;
    const loggedLaunched = new Promise<void>(resolve => {
      announceLaunched = resolve;
    });

    const observe = (next: number) => {
      if (cancelled) {
        return;
      }
      setStatus(previous => {
        if (previous !== next) {
          // The e2e's marker. Also the only way to see the Launching →
          // Launched transition on a device without attaching a debugger.
          console.log(`BUGSEE_E2E status=${next} (${STATUS_NAMES[next]})`);
          if (next === Status.Launched) {
            announceLaunched();
          }
        }
        return next;
      });
    };

    (async () => {
      const token = appToken();
      if (!token) {
        setError(`no ${Platform.OS} token — run scripts/write-credentials.mjs`);
        return;
      }
      console.log(`BUGSEE_E2E launching on ${Platform.OS}`);
      // Polling starts before launch() is awaited, not after. The SDK brings
      // capture up off the main thread, so by the time the promise resolves the
      // status is usually already Launched and the Launching state would never
      // be observed — the very transition this example exists to show.
      poll = setInterval(() => {
        Bugsee.getStatus().then(observe).catch(() => {});
      }, 100);
      try {
        const launched = await Bugsee.launch(token, endpointOption(credentials.endpoint));
        console.log(`BUGSEE_E2E launch() resolved ${String(launched)}`);

        // Wait for Launched to be LOGGED before relaunching, so the output
        // order is deterministic: status=2, then relaunch, then status=2
        // again. Firing relaunch as soon as launch() resolves races the
        // status poll, and the e2e matches its steps in order.
        await loggedLaunched;

        // relaunch() is the one lifecycle call whose two platforms settle
        // through different SDK machinery: Android hands back a boolean, iOS
        // reports through a `started:` completion block that the SDK can fail
        // to invoke. What the e2e asserts is that the promise SETTLES -- a
        // promise that never settles is indistinguishable from a slow one,
        // and no other check in this repo would notice.
        try {
          const relaunched = await Bugsee.relaunch(
            endpointOption(credentials.endpoint),
          );
          console.log(`BUGSEE_E2E relaunch() settled resolved=${String(relaunched)}`);
        } catch (relaunchCause) {
          console.log(`BUGSEE_E2E relaunch() settled rejected=${String(relaunchCause)}`);
        }

        // Asserted separately from the status poll: a successful relaunch
        // completes in about 10ms, so the 100ms poll observes no change and
        // logs nothing. Reading the status here is what proves capture
        // actually came back up.
        console.log(
          `BUGSEE_E2E post-relaunch status=${await Bugsee.getStatus()}`,
        );
      } catch (cause) {
        console.log(`BUGSEE_E2E launch() threw ${String(cause)}`);
        if (!cancelled) {
          setError(String(cause));
        }
      }
    })();

    return () => {
      cancelled = true;
      if (poll !== undefined) {
        clearInterval(poll);
      }
    };
  }, []);

  return (
    <View style={styles.screen}>
      <View style={styles.card}>
        <Text style={styles.title}>Bugsee React Native</Text>
        <Text style={styles.label}>status</Text>
        <Text testID="status" style={styles.status}>
          {STATUS_NAMES[status] ?? `unknown (${status})`}
        </Text>
        {error !== undefined && <Text style={styles.error}>{error}</Text>}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#11131a' },
  card: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  title: { color: '#8a94a6', fontSize: 16, marginBottom: 32 },
  label: { color: '#5c6577', fontSize: 12, letterSpacing: 2 },
  status: { color: '#f5f7fa', fontSize: 40, fontWeight: '600', marginTop: 8 },
  error: { color: '#ff6b6b', fontSize: 13, marginTop: 24, textAlign: 'center' },
});
