/**
 * `credentials.json` is generated by scripts/write-credentials.mjs and is
 * gitignored, so it is absent on a fresh checkout. Declaring its shape lets
 * the example typecheck without the secret file existing — and pins the shape,
 * so a change to the generator that this file does not follow is a type error
 * rather than an undefined at runtime.
 */
declare module '*/credentials.json' {
  const credentials: {
    ios: string;
    android: string;
    endpoint: string;
  };
  export default credentials;
}
