#!/usr/bin/env bash
#
# Checks that our TurboModule spec and TypeScript still work on one React
# Native version, without building an app.
#
# Why not just build the example on each version: the example's android/ and
# ios/ projects are generated by a specific React Native template, and swapping
# the npm dependency does not swap the project. Pinning the example to 0.81 and
# building it fails inside React Native's OWN gradle-plugin sources, which the
# 0.87 template's Kotlin toolchain cannot compile — nothing to do with this
# wrapper. A real per-version app build needs a per-version generated app; see
# the plan. This checks the surface that is actually ours.
#
# Usage: check-rn-compat.sh 0.81
set -euo pipefail

RN="${1:?usage: check-rn-compat.sh <react-native minor, e.g. 0.81>}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "--- installing react-native@~${RN}.0"
cd "$WORK"
echo '{ "name": "rn-compat-probe", "version": "0.0.0", "private": true }' > package.json
# @types/react: <BugseeSecure> is .tsx, and the automatic JSX runtime and the
# hooks it uses are typed there, not by react-native.
npm i --silent --no-audit --no-fund "react-native@~${RN}.0" "@react-native/codegen@~${RN}.0" typescript@5.6 "@types/react@19" >/dev/null
ACTUAL="$(node -p "require('react-native/package.json').version")"
echo "    resolved ${ACTUAL}"

echo "--- view-tree internals guard"
# src/viewtree/fiber.ts and walk.ts (Task 6.3) are the only modules that read
# React / React Native internals, and they depend on several things staying
# put. This fails loudly, with a named reason, the day any of them move —
# instead of the view-tree walk silently going blind on a device. Every check
# below matches an actual definition/assignment/call, not merely a mention —
# a comment, an import, or a type declaration must not satisfy it.
RN_SRC="node_modules/react-native"

# (1) getPublicInstanceFromInternalInstanceHandle is what turns the fiber's
# internal instance handle into the public instance `measureInWindow` lives
# on. fiber.ts imports it from RendererProxy, which only re-exports it
# (`export * from './RendererImplementation'`) — so both the actual
# definition in RendererImplementation.js and RendererProxy.js's re-export of
# it (directly or via the star-export) must hold.
RENDERER_IMPL="$RN_SRC/Libraries/ReactNative/RendererImplementation.js"
RENDERER_PROXY="$RN_SRC/Libraries/ReactNative/RendererProxy.js"
[ -f "$RENDERER_IMPL" ] \
  || { echo "FAIL: RendererImplementation.js not found"; exit 1; }
grep -qE 'export (const|function) getPublicInstanceFromInternalInstanceHandle' "$RENDERER_IMPL" \
  || { echo "FAIL: getPublicInstanceFromInternalInstanceHandle is not defined (export const|function) in RendererImplementation.js"; exit 1; }
[ -f "$RENDERER_PROXY" ] \
  || { echo "FAIL: RendererProxy.js not found"; exit 1; }
grep -qE "export (const|function) getPublicInstanceFromInternalInstanceHandle|export \\* from '\\./RendererImplementation'" "$RENDERER_PROXY" \
  || { echo "FAIL: RendererProxy.js neither re-exports RendererImplementation nor defines getPublicInstanceFromInternalInstanceHandle itself"; exit 1; }
echo "    getPublicInstanceFromInternalInstanceHandle is defined and reachable through RendererProxy"

# (2) __internalInstanceHandle is what fiberRootOf walks up from — an actual
# assignment (`.__internalInstanceHandle = …`), not a read (both
# ReactFabricPublicInstance.js and the Flow field declaration in
# ReactNativeElement.js itself would otherwise satisfy a bare-name grep) and
# not a type declaration. ReactNativeElement.js assigns it on every supported
# version; ReactFabricHostComponent.js also did through 0.81, then was
# deleted outright (not folded into ReactFabricPublicInstance.js, which only
# ever reads the field) by 0.87 — checked only when the file still exists, so
# its removal is reported, not silently treated as a pass via a substitute.
#
# N4 (review round 1): a plain `[[:space:]]*=` also matches `==`/`===`
# (a *comparison*, e.g. `if (this.__internalInstanceHandle == null)`, found
# on ReactFabricPublicInstance.js — a file this guard does not even check
# today, but the imprecision is in the pattern itself, not in which file
# happens to be safe from it right now) and matches equally inside a comment
# line (a commented-out assignment, or a JSDoc mention of the field, would
# vacuously satisfy it). `=([^=]|$)` requires the `=` immediately after the
# field name not to be followed by a second `=`; comment lines (their first
# non-space characters `//` or `*`, covering both `//` line comments and a
# `/** … */`/JSDoc block's continuation lines) are filtered out first.
assigns_handle() {
  grep -v -E '^[[:space:]]*(//|\*)' "$1" | grep -qE '\.__internalInstanceHandle[[:space:]]*=([^=]|$)'
}

ELEMENT_FILE="$RN_SRC/src/private/webapis/dom/nodes/ReactNativeElement.js"
[ -f "$ELEMENT_FILE" ] \
  || { echo "FAIL: ReactNativeElement.js not found"; exit 1; }
assigns_handle "$ELEMENT_FILE" \
  || { echo "FAIL: no __internalInstanceHandle ASSIGNMENT found in ReactNativeElement.js (a read, a comparison or a Flow field declaration does not count)"; exit 1; }
echo "    __internalInstanceHandle is assigned in ReactNativeElement.js"

HOST_COMPONENT_FILE="$RN_SRC/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricHostComponent.js"
if [ -f "$HOST_COMPONENT_FILE" ]; then
  assigns_handle "$HOST_COMPONENT_FILE" \
    || { echo "FAIL: ReactFabricHostComponent.js exists but no longer assigns __internalInstanceHandle"; exit 1; }
  echo "    __internalInstanceHandle is also assigned in ReactFabricHostComponent.js (legacy Fabric public instance, still present)"
else
  echo "    ReactFabricHostComponent.js removed (0.8x+) — ReactNativeElement is the only public instance"
fi

# (3) measureHostFiber assumes measureInWindow's native callback runs
# synchronously (it reads the result the same tick, never awaiting a
# promise). Two independent public-instance shapes can come back from
# getPublicInstanceFromInternalInstanceHandle, and both must be checked:
# - ReactNativeElement.js's measureInWindow (the DOM-node instance, the only
#   one left once ReactFabricHostComponent.js is gone) calls
#   NativeDOM::measureInWindow in NativeDOM.cpp;
# - ReactFabricHostComponent.js's measureInWindow (legacy, while it exists)
#   calls into UIManagerBinding.cpp's own "measureInWindow" branch.
# Both are tightened to require the real rect (`rect.x`/`rect.width`) reaching
# the callback synchronously in the same function body, not just any
# `callback(`/`callback.call(` — which a `{0,0,0,0}` early-return stub, or an
# unrelated call, would also match.
# A Node check, not grep: the method spans several lines, and plain `grep`
# matches one line at a time — it can never see a call that is not on the
# same line as the method's own name.
node -e '
  const fs = require("fs");
  const src = fs.readFileSync(process.argv[1], "utf8");
  const marker = "measureInWindow(callback";
  const start = src.indexOf(marker);
  if (start === -1) {
    console.error("FAIL: no measureInWindow(callback...) method found in ReactNativeElement.js");
    process.exit(1);
  }
  const body = src.slice(start, start + 400);
  if (!body.includes("NativeDOM.measureInWindow(")) {
    console.error("FAIL: ReactNativeElement.js'"'"'s measureInWindow no longer calls NativeDOM.measureInWindow(...)");
    process.exit(1);
  }
' "$ELEMENT_FILE"
echo "    ReactNativeElement.js's measureInWindow calls NativeDOM.measureInWindow"

NATIVE_DOM_CPP="$RN_SRC/ReactCommon/react/nativemodule/dom/NativeDOM.cpp"
[ -f "$NATIVE_DOM_CPP" ] \
  || { echo "FAIL: NativeDOM.cpp not found — the DOM-node measureInWindow path cannot be checked"; exit 1; }
node -e '
  const fs = require("fs");
  const src = fs.readFileSync(process.argv[1], "utf8");
  const marker = "NativeDOM::measureInWindow(";
  const start = src.indexOf(marker);
  if (start === -1) {
    console.error("FAIL: NativeDOM::measureInWindow not found in NativeDOM.cpp");
    process.exit(1);
  }
  const nextFn = src.indexOf("NativeDOM::", start + marker.length);
  const body = src.slice(start, nextFn === -1 ? undefined : nextFn);
  const callsBack = /callback\.call\(|callback\(/.test(body);
  if (!callsBack || !body.includes("rect.x") || !body.includes("rect.width")) {
    console.error(
      "FAIL: NativeDOM::measureInWindow no longer calls its callback synchronously with the real rect (rect.x/rect.width)",
    );
    process.exit(1);
  }
' "$NATIVE_DOM_CPP"
echo "    NativeDOM::measureInWindow calls its callback synchronously with the real rect"

NATIVE_DOM_H="$RN_SRC/ReactCommon/react/nativemodule/dom/NativeDOM.h"
if [ -f "$NATIVE_DOM_H" ] && grep -q 'MeasureInWindowOnSuccessCallback' "$NATIVE_DOM_H"; then
  grep -qE 'MeasureInWindowOnSuccessCallback[[:space:]]*=[[:space:]]*SyncCallback' "$NATIVE_DOM_H" \
    || { echo "FAIL: NativeDOM.h's MeasureInWindowOnSuccessCallback is no longer a SyncCallback"; exit 1; }
  echo "    NativeDOM.h declares MeasureInWindowOnSuccessCallback as a SyncCallback"
else
  echo "    NativeDOM.h has no separate MeasureInWindowOnSuccessCallback alias on this version (measureInWindow takes a plain jsi::Function) — synchronicity is proven by the .cpp body above regardless"
fi

if [ -f "$HOST_COMPONENT_FILE" ]; then
  node -e '
    const fs = require("fs");
    const src = fs.readFileSync(process.argv[1], "utf8");
    const marker = "measureInWindow(callback";
    const start = src.indexOf(marker);
    if (start === -1) {
      console.error("FAIL: no measureInWindow(callback...) method found in ReactFabricHostComponent.js");
      process.exit(1);
    }
    const body = src.slice(start, start + 400);
    if (!body.includes("fabricMeasureInWindow(")) {
      console.error("FAIL: ReactFabricHostComponent.js'"'"'s measureInWindow no longer calls the Fabric UIManager'"'"'s measureInWindow");
      process.exit(1);
    }
  ' "$HOST_COMPONENT_FILE"
  echo "    ReactFabricHostComponent.js's measureInWindow calls the Fabric UIManager"

  BINDING_CPP="$RN_SRC/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp"
  [ -f "$BINDING_CPP" ] \
    || { echo "FAIL: UIManagerBinding.cpp not found — the legacy measureInWindow path cannot be checked"; exit 1; }
  node -e '
    const fs = require("fs");
    const src = fs.readFileSync(process.argv[1], "utf8");
    const marker = "\"measureInWindow\"";
    const start = src.indexOf(marker);
    if (start === -1) {
      console.error("FAIL: no measureInWindow branch found in UIManagerBinding.cpp");
      process.exit(1);
    }
    const nextBranch = src.indexOf("if (methodName ==", start + marker.length);
    const branch = src.slice(start, nextBranch === -1 ? undefined : nextBranch);
    const callsBack = /callbackFunction\.call\(|callbackFunction\(/.test(branch);
    if (!callsBack || !branch.includes("rect.x") || !branch.includes("rect.width")) {
      console.error(
        "FAIL: the measureInWindow branch of UIManagerBinding.cpp no longer calls its callback synchronously with the real rect",
      );
      process.exit(1);
    }
  ' "$BINDING_CPP"
  echo "    UIManagerBinding.cpp's measureInWindow branch calls its callback synchronously with the real rect (legacy path, still present)"
else
  echo "    ReactFabricHostComponent.js removed — the legacy UIManagerBinding.cpp measureInWindow path is not reachable and is not checked"
fi

# (4) Offscreen/LegacyHidden hidden detection (walk.ts's isHidden) reads
# `memoizedState`, which React's updateOffscreenComponent sets to a
# `{ baseLanes, cachePool }` object while hidden and to `null` while visible —
# checked directly in the bundled renderer (both dev, for readable stack
# traces in a debug build, and prod, where the property names survive
# minification) so a shape change here is caught the same way a moved
# internal would be, not left to fiber.ts's stale-comment fate from before.
# The two fiber-tag literals `isHidden`/`classify` switch on for SimpleMemo
# and Offscreen are pinned at one distinctive, stable call site each — a
# renderer that renumbers React's own work tags would fail here first.
for RENDERER_BUNDLE in \
  "$RN_SRC/Libraries/Renderer/implementations/ReactFabric-dev.js" \
  "$RN_SRC/Libraries/Renderer/implementations/ReactFabric-prod.js"
do
  BUNDLE_NAME="$(basename "$RENDERER_BUNDLE")"
  [ -f "$RENDERER_BUNDLE" ] \
    || { echo "FAIL: $BUNDLE_NAME not found"; exit 1; }
  grep -qE 'baseLanes:[[:space:]]*0,[[:space:]]*cachePool:[[:space:]]*null' "$RENDERER_BUNDLE" \
    || { echo "FAIL: $BUNDLE_NAME no longer sets memoizedState to { baseLanes, cachePool } for a hidden Offscreen fiber"; exit 1; }
  grep -qE '\.tag = 15\b' "$RENDERER_BUNDLE" \
    || { echo "FAIL: $BUNDLE_NAME no longer downgrades a plain-function memo() fiber to tag 15 (SimpleMemo)"; exit 1; }
  grep -qE '22 === [a-zA-Z_$]+\.tag' "$RENDERER_BUNDLE" \
    || { echo "FAIL: $BUNDLE_NAME no longer compares a fiber's tag against 22 (Offscreen)"; exit 1; }
done
echo "    Offscreen's hidden signal (memoizedState) and the SimpleMemo/Offscreen tag numbers are unchanged in both renderer bundles"

# A package shaped like ours, carrying the real codegenConfig and the real spec.
mkdir -p pkg/src
# -R, not src/*.ts: the source tree has subdirectories (options/, wrapper/),
# and copying only the top level leaves index.ts importing modules that are
# not there. Tests are excluded because they need jest types this probe has
# no reason to install.
cp -R "$REPO"/packages/react-native/src/. pkg/src/
rm -rf pkg/src/__tests__ pkg/src/__mocks__ pkg/src/*/__tests__
node -e "
  const p = require('$REPO/packages/react-native/package.json');
  require('fs').writeFileSync('pkg/package.json', JSON.stringify({
    name: p.name, version: p.version, codegenConfig: p.codegenConfig,
  }, null, 2));
"

echo "--- iOS codegen"
# From 0.83 the generator refuses to run without a native project, because it
# computes spec paths relative to one. A stub directory satisfies that without
# fabricating a whole app.
mkdir -p pkg/Probe.xcodeproj
node node_modules/react-native/scripts/generate-codegen-artifacts.js -p ./pkg -o ./out -t ios >/dev/null

# The TurboModule name collides with the SDK's own Bugsee class: React Native
# falls back to NSClassFromString(@"Bugsee"), which resolves to the SDK, not
# the module. codegenConfig.ios.modulesProvider is the fix, and this asserts
# the version under test still honours it.
# Located rather than hardcoded: 0.83 moved these under a ReactCodegen/
# subdirectory, and a fixed path silently finds nothing.
PROVIDER="$(find out -name RCTModuleProviders.mm | head -1)"
[ -n "$PROVIDER" ] || { echo "FAIL: RCTModuleProviders.mm was not generated"; exit 1; }
grep -q '@"Bugsee": @"BugseeModule"' "$PROVIDER" \
  || { echo "FAIL: modulesProvider mapping missing from $PROVIDER"; exit 1; }
echo "    modulesProvider maps Bugsee -> BugseeModule"

SPEC_H="$(find out -name RNBugseeSpec.h | head -1)"
[ -n "$SPEC_H" ] || { echo "FAIL: RNBugseeSpec.h was not generated"; exit 1; }
grep -q '@protocol NativeBugseeSpec' "$SPEC_H" \
  || { echo "FAIL: NativeBugseeSpec protocol not generated"; exit 1; }
echo "    NativeBugseeSpec protocol generated"

# Object payloads with nullable members cross as JSON text, not UnsafeObject
# (src/bridge/json.ts): RN's iOS conversion of an object argument drops every
# null member unless an app-level flag is on, so a `null` meant "clear" on
# Android and nothing on iOS. Assert this version generates the two such
# methods with NSString parameters, under the selectors BugseeModule.mm
# implements (ios-spec-coverage.test.ts pins the module side). Whitespace is
# collapsed first: codegen aligns multi-line selectors on their colons.
node -e '
  const header = require("fs").readFileSync(process.argv[1], "utf8").replace(/\s+/g, " ");
  const wanted = [
    "- (void)event:(NSString *)name paramsJson:(NSString * _Nullable)paramsJson;",
    "- (void)reportUpdate:(NSString *)handleId patchJson:(NSString *)patchJson " +
      "resolve:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject;",
  ];
  for (const declaration of wanted) {
    if (!header.includes(declaration)) {
      console.error("FAIL: the generated protocol does not declare " + declaration);
      process.exit(1);
    }
  }
' "$SPEC_H"
echo "    event and reportUpdate take their object payloads as JSON text (NSString)"

echo "--- Android codegen"
# Deliberately NOT generate-codegen-artifacts.js: the app-level executor
# hardcodes com.facebook.fbreact.specs and ignores javaPackageName, so probing
# through it reads as a failure when nothing is wrong. Only the Gradle task and
# this CLI honour the setting.
node node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js \
  --platform android schema.json ./pkg/src >/dev/null
node node_modules/react-native/scripts/generate-specs-cli.js \
  --platform android --schemaPath schema.json --outputDir ./outj \
  --libraryName RNBugseeSpec --javaPackageName com.bugsee.reactnative >/dev/null

SPEC=outj/java/com/bugsee/reactnative/NativeBugseeSpec.java
[ -f "$SPEC" ] || { echo "FAIL: javaPackageName ignored — no $SPEC"; exit 1; }
echo "    honours javaPackageName"

# Compare the generated abstract signatures against what BugseeModule.java
# ACTUALLY implements. The comparison lives in scripts/java-signatures.ts,
# where it is unit-tested: it was previously a list of string literals in this
# script that never opened the module, and then a sed pipeline that silently
# mangled its input on BSD sed.
node "$REPO/scripts/cli-check-java-signatures.ts" \
  "$SPEC" \
  "$REPO/packages/react-native/android/src/main/java/com/bugsee/reactnative/BugseeModule.java"

echo "--- typecheck against ${ACTUAL}'s types"
mkdir -p tscheck
cp -R "$REPO"/packages/react-native/src/. tscheck/
rm -rf tscheck/__tests__ tscheck/__mocks__ tscheck/*/__tests__
node -e "
  const fs = require('fs');
  // Strip comments: the repo's tsconfig is JSONC, JSON.parse is not.
  const base = fs.readFileSync('$REPO/tsconfig.base.json', 'utf8')
    .replace(/^\s*\/\/.*$/gm, '');
  const co = JSON.parse(base).compilerOptions;
  co.noEmit = true; delete co.declaration;
  fs.writeFileSync('tsconfig.json', JSON.stringify(
    { compilerOptions: co, include: ['tscheck/**/*.ts', 'tscheck/**/*.tsx'] }, null, 2));
"
./node_modules/.bin/tsc -p tsconfig.json
echo "    typecheck clean"

echo "PASS react-native ${ACTUAL}"
