#!/usr/bin/env bash
#
# Checks that our TurboModule spec and TypeScript still work on one React
# Native version, without building an app.
#
# Why not just build the example on each version: the example's android/ and
# ios/ projects are generated by a specific React Native template, and swapping
# the npm dependency does not swap the project. Pinning the example to 0.81 and
# building it fails inside React Native's OWN gradle-plugin sources, which the
# 0.87 template's Kotlin toolchain cannot compile — nothing to do with this
# wrapper. A real per-version app build needs a per-version generated app; see
# the plan. This checks the surface that is actually ours.
#
# Usage: check-rn-compat.sh 0.81
set -euo pipefail

RN="${1:?usage: check-rn-compat.sh <react-native minor, e.g. 0.81>}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "--- installing react-native@~${RN}.0"
cd "$WORK"
echo '{ "name": "rn-compat-probe", "version": "0.0.0", "private": true }' > package.json
npm i --silent --no-audit --no-fund "react-native@~${RN}.0" "@react-native/codegen@~${RN}.0" typescript@5.6 >/dev/null
ACTUAL="$(node -p "require('react-native/package.json').version")"
echo "    resolved ${ACTUAL}"

# A package shaped like ours, carrying the real codegenConfig and the real spec.
mkdir -p pkg/src
cp "$REPO"/packages/react-native/src/*.ts pkg/src/
node -e "
  const p = require('$REPO/packages/react-native/package.json');
  require('fs').writeFileSync('pkg/package.json', JSON.stringify({
    name: p.name, version: p.version, codegenConfig: p.codegenConfig,
  }, null, 2));
"

echo "--- iOS codegen"
# From 0.83 the generator refuses to run without a native project, because it
# computes spec paths relative to one. A stub directory satisfies that without
# fabricating a whole app.
mkdir -p pkg/Probe.xcodeproj
node node_modules/react-native/scripts/generate-codegen-artifacts.js -p ./pkg -o ./out -t ios >/dev/null

# The TurboModule name collides with the SDK's own Bugsee class: React Native
# falls back to NSClassFromString(@"Bugsee"), which resolves to the SDK, not
# the module. codegenConfig.ios.modulesProvider is the fix, and this asserts
# the version under test still honours it.
# Located rather than hardcoded: 0.83 moved these under a ReactCodegen/
# subdirectory, and a fixed path silently finds nothing.
PROVIDER="$(find out -name RCTModuleProviders.mm | head -1)"
[ -n "$PROVIDER" ] || { echo "FAIL: RCTModuleProviders.mm was not generated"; exit 1; }
grep -q '@"Bugsee": @"BugseeModule"' "$PROVIDER" \
  || { echo "FAIL: modulesProvider mapping missing from $PROVIDER"; exit 1; }
echo "    modulesProvider maps Bugsee -> BugseeModule"

SPEC_H="$(find out -name RNBugseeSpec.h | head -1)"
[ -n "$SPEC_H" ] || { echo "FAIL: RNBugseeSpec.h was not generated"; exit 1; }
grep -q '@protocol NativeBugseeSpec' "$SPEC_H" \
  || { echo "FAIL: NativeBugseeSpec protocol not generated"; exit 1; }
echo "    NativeBugseeSpec protocol generated"

echo "--- Android codegen"
# Deliberately NOT generate-codegen-artifacts.js: the app-level executor
# hardcodes com.facebook.fbreact.specs and ignores javaPackageName, so probing
# through it reads as a failure when nothing is wrong. Only the Gradle task and
# this CLI honour the setting.
node node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js \
  --platform android schema.json ./pkg/src >/dev/null
node node_modules/react-native/scripts/generate-specs-cli.js \
  --platform android --schemaPath schema.json --outputDir ./outj \
  --libraryName RNBugseeSpec --javaPackageName com.bugsee.reactnative >/dev/null

SPEC=outj/java/com/bugsee/reactnative/NativeBugseeSpec.java
[ -f "$SPEC" ] || { echo "FAIL: javaPackageName ignored — no $SPEC"; exit 1; }
echo "    honours javaPackageName"

# The abstract signatures the shipped BugseeModule.java implements. If codegen
# changes one, the module stops compiling in a consuming app — and nothing
# else in CI would notice until someone built one.
for sig in \
  'public abstract void launch(String token, ReadableMap options, Promise promise);' \
  'public abstract void relaunch(ReadableMap options, Promise promise);' \
  'public abstract void stop(Promise promise);' \
  'public abstract void getStatus(Promise promise);' \
  'public abstract void testCrash();'
do
  grep -qF "$sig" "$SPEC" || { echo "FAIL: signature changed or missing: $sig"; exit 1; }
done
echo "    generated signatures match what BugseeModule.java implements"

echo "--- typecheck against ${ACTUAL}'s types"
mkdir -p tscheck && cp "$REPO"/packages/react-native/src/*.ts tscheck/
node -e "
  const fs = require('fs');
  // Strip comments: the repo's tsconfig is JSONC, JSON.parse is not.
  const base = fs.readFileSync('$REPO/tsconfig.base.json', 'utf8')
    .replace(/^\s*\/\/.*$/gm, '');
  const co = JSON.parse(base).compilerOptions;
  co.noEmit = true; delete co.declaration;
  fs.writeFileSync('tsconfig.json', JSON.stringify(
    { compilerOptions: co, include: ['tscheck/**/*.ts'] }, null, 2));
"
./node_modules/.bin/tsc -p tsconfig.json
echo "    typecheck clean"

echo "PASS react-native ${ACTUAL}"
